
// This file has been generated by the GUI designer. Do not modify.
namespace Tests
{
	public partial class Controller
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Tests.Controller
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Tests.Controller";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
